-- Persistent problem bank. Keep it outside `public` so the Supabase Data API
-- cannot expose private tests or reference solutions.
create schema if not exists dojo;
revoke all on schema dojo from public, anon, authenticated;

create table if not exists dojo.problem_bank_state (
  singleton boolean primary key default true check (singleton),
  bank_version bigint not null check (bank_version >= 1),
  updated_at timestamptz not null default now()
);

insert into dojo.problem_bank_state (singleton, bank_version)
values (true, 1)
on conflict (singleton) do nothing;

create table if not exists dojo.problems (
  id text primary key check (id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  version integer not null check (version >= 1),
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  title text not null check (length(btrim(title)) between 1 and 80),
  public_data jsonb not null check (jsonb_typeof(public_data) = 'object'),
  private_data jsonb not null check (jsonb_typeof(private_data) = 'object'),
  sort_order bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (public_data ->> 'id' = id),
  check (private_data ->> 'problem_id' = id),
  check ((public_data ->> 'version')::integer = version),
  check ((private_data ->> 'version')::integer = version),
  check (public_data ->> 'difficulty' = difficulty)
);

revoke all on all tables in schema dojo from public, anon, authenticated;
revoke all on all sequences in schema dojo from public, anon, authenticated;
